#!/bin/bash

# encryption: https://www.gnupg.org/gph/en/manual.html#AEN111
# git hooks: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
# adding files to git on pre_commit hook:
# http://stackoverflow.com/questions/3284292/can-a-git-hook-automatically-add-files-to-the-commit

SCRIPT_DIR=".secrets"


function _check_setup {
  if [[ ! -d ".git" ]] || [[ ! -d ".git/hooks" ]]; then
    echo "repository is broken. try running 'git init' or 'git clone'"
    exit 1
  fi
}


function _init_script {
  if [[ $# == 0 ]]; then
    usage "no input parameters provided."
  fi

  # checking for proper set-up:
  _check_setup

  # load dependencies:
  for f in ${0%/*}/bin/*; do [[ -f "$f" ]] && . "$f"; done

  # routing the input command:
  if [[ `_function_exists $1` == 0 ]] && [[ ! $1 == _* ]]; then
    $1 "${@:2}"
  else
    usage "command ${1} not found."
  fi
}

_init_script $@
