---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ test_dependencies }}"

- name: Get bats
  git:
    repo: 'https://github.com/sstephenson/bats.git'
    dest: /opt/bats

- name: Install bats
  file:
    src: /opt/bats/libexec/bats
    dest: /usr/bin/bats
    state: link

- name: Get ShellCheck
  get_url:
    url: https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
    dest: /tmp/shellcheck.tar.xz

- name: Install ShellCheck
  command: tar xvf /tmp/shellcheck.tar.xz -C /usr/bin --strip-components=1
  args:
    warn: no
    creates: /usr/bin/shellcheck

- name: Install fpm
  gem:
    name: fpm
    state: present
    user_install: no
