---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ test_dependencies }}"

- name: Get ShellCheck
  get_url:
    url: https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
    dest: /tmp/shellcheck.tar.xz

- name: Install ShellCheck
  command: tar xvf /tmp/shellcheck.tar.xz -C /usr/bin --strip-components=1
  args:
    warn: no
    creates: /usr/bin/shellcheck

- name: Install fpm
  gem:
    name: fpm
    state: present
    user_install: no

# here the package is installed but a non-zero status code is returned that we ignore
- name: Install apk packaging dependencies for Alpine based distros
  command: bash -lc "gem install etc || :"
  when:
    - ansible_os_family == "Alpine"

- name: Download and install Mozilla Sops
  get_url:
    url: https://github.com/mozilla/sops/releases/download/3.2.0/sops-3.2.0.linux
    dest: /usr/bin/sops
    mode: 0755
