.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SECRET\-TELL" "1" "September 2022" "sobolevn" "git-secret 0.5.1-alpha1"
.
.SH "NAME"
\fBgit\-secret\-tell\fR \- adds person who can access private data\.
.
.SH "SYNOPSIS"
.
.nf

git secret tell [\-m] [\-d dir] [emails]\.\.\.
.
.fi
.
.SH "DESCRIPTION"
\fBgit\-secret tell\fR \- adds user(s) to the list of those able to encrypt/decrypt secrets\.
.
.P
This lets the specified user encrypt new files, but will not immediately be able to decrypt existing files, which were encrypted without their key\. Files should be re\-encrypted with the new keyring by someone who already has access in order for the new user to be able to decrypt the files\.
.
.P
\fBgit\-secret tell\fR works only with email addresses, and will exit with an error if you have multiple keys in your keyring with specified email addresses, or if one of the specified emails is already associated with a key in the \fBgit\-secret\fR repo\'s keyring\.
.
.P
Under the hood, \fBgit\-secret\-tell\fR searches in the current user\'s \fBgnupg\fR keyring for public key(s) of passed email(s), then imports the corresponding public key(s) into your \fBgit\-secret\fR repo\'s keyring\.
.
.P
Versions of \fBgit\-secret tell\fR after \fB0\.3\.2\fR will warn about keys that are expired, revoked, or otherwise invalid\. It will also warn if multiple keys are found for a single email address\.
.
.P
\fBDo not manually import secret keys into \fBgit\-secret\fR\fR\. It won\'t work with imported secret keys anyway\.
.
.P
For more details about how \fBgit\-secret\fR uses public and private keys, see the documentation for \fBgit\-secret\-hide\fR and \fBgit\-secret\-reveal\fR\.
.
.SH "OPTIONS"
.
.nf

\-m  \- uses your current `git config user\.email` setting as an identifier for the key\.
\-d  \- specifies `\-\-homedir` option for `gpg`, basically use this option if your store your keys in a custom location\.
\-h  \- shows help\.
.
.fi
.
.SH "MANUAL"
Run \fBman git\-secret\-tell\fR to see this document\.
.
.SH "SEE ALSO"
git\-secret\-init(1) \fIhttps://git\-secret\.io/git\-secret\-init\fR, git\-secret\-add(1) \fIhttps://git\-secret\.io/git\-secret\-add\fR, git\-secret\-hide(1) \fIhttps://git\-secret\.io/git\-secret\-hide\fR, git\-secret\-reveal(1) \fIhttps://git\-secret\.io/git\-secret\-reveal\fR, git\-secret\-cat(1) \fIhttps://git\-secret\.io/git\-secret\-cat\fR, git\-secret\-removeperson(1) \fIhttps://git\-secret\.io/git\-secret\-removeperson\fR
