.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SECRET\-REMOVEPERSON" "1" "September 2024" "sobolevn" "git-secret 0.5.1-alpha1"
.
.SH "NAME"
\fBgit\-secret\-removeperson\fR \- removes user\'s public key from repo keyring\.
.
.SH "SYNOPSIS"
.
.nf

git secret removeperson <emails>\.\.\.
.
.fi
.
.SH "DESCRIPTION"
\fBgit\-secret\-removeperson\fR \- removes public keys for passed email addresses from repo\'s \fBgit\-secret\fR keyring\.
.
.P
This command is used to begin the process of disallowing a user from encrypting and decrypting secrets with \fBgit\-secret\fR\.
.
.P
If you remove a user\'s access with \fBgit\-secret\-removeperson\fR, and then run \fBgit\-secret\-reveal\fR and \fBgit\-secret\-hide \-r\fR, that user will no longer be able user to decrypt the hidden files\.
.
.SH "OPTIONS"
.
.nf

\-h  \- shows this help\.
.
.fi
.
.SH "MANUAL"
Run \fBman git\-secret\-removeperson\fR to see this document\.
.
.SH "SEE ALSO"
git\-secret\-tell(1) \fIhttps://git\-secret\.io/git\-secret\-tell\fR, git\-secret\-remove(1) \fIhttps://git\-secret\.io/git\-secret\-remove\fR, git\-secret\-clean(1) \fIhttps://git\-secret\.io/git\-secret\-clean\fR
