.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SECRET\-CLEAN" "1" "March 2023" "sobolevn" "git-secret 0.5.1-alpha1"
.
.SH "NAME"
\fBgit\-secret\-clean\fR \- removes all the hidden files\.
.
.SH "SYNOPSIS"
.
.nf

git secret clean [\-v]
.
.fi
.
.SH "DESCRIPTION"
\fBgit\-secret\-clean\fR \- deletes all files in the current \fBgit\-secret\fR repo that end with \fB\.secret\fR\.
.
.P
You can change the extension \fBgit\-secret\fR uses for encrypted files with the \fBSECRETS_EXTENSION\fR environment variable\.
.
.P
Note that it will delete any files ending in \fB\.secret\fR, even if they are not tracked by \fBgit\-secret\fR\.
.
.P
Also note that this command does not delete unencrypted versions of files\.
.
.P
Verbose mode, enabled with the \fB\-v\fR option, displays the filenames deleted\.
.
.SH "OPTIONS"
.
.nf

\-v  \- verbose mode, shows which files are deleted\.
\-h  \- shows this help\.
.
.fi
.
.P
You can also enable verbosity using the SECRETS_VERBOSE environment variable, as documented at git\-secret(7) \fIhttps://git\-secret\.io/\fR
.
.SH "MANUAL"
Run \fBman git\-secret\-clean\fR to see this document\.
.
.SH "SEE ALSO"
git\-secret\-whoknows(1) \fIhttps://git\-secret\.io/git\-secret\-whoknows\fR, git\-secret\-add(1) \fIhttps://git\-secret\.io/git\-secret\-add\fR, git\-secret\-remove(1) \fIhttps://git\-secret\.io/git\-secret\-remove\fR, git\-secret\-removeperson(1) \fIhttps://git\-secret\.io/git\-secret\-removeperson\fR
