.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SECRET\-INIT" "1" "September 2024" "sobolevn" "git-secret 0.5.1-alpha1"
.
.SH "NAME"
\fBgit\-secret\-init\fR \- initializes git\-secret repository\.
.
.SH "SYNOPSIS"
.
.nf

git secret init
.
.fi
.
.SH "DESCRIPTION"
\fBgit\-secret\-init\fR \- initializes a \fBgit\-secret\fR repo by setting up a \fB\.gitsecret\fR directory\.
.
.P
\fBgit\-secret\-init\fR should be run inside a \fBgit\fR repo, to create the \fB\.gitsecret\fR directory and initialize the repo for git\-secret\. Until a repository is initialized with \fBgit secret init\fR, all other \fBgit\-secret\fR commands are unavailable\.
.
.P
If a \fB\.gitsecret\fR directory already exists, \fBgit\-secret\-init\fR exits without making any changes\. Otherwise,
.
.IP "\(bu" 4
\fB\.gitignore\fR is modified to ignore \fBgit\-secret\fR\'s \fBrandom_seed_file\fR, and to not ignore \fB\.secret\fR files,
.
.IP "\(bu" 4
a \.gitsecret directory is created with the sub\-directories /keys and /paths,
.
.IP "\(bu" 4
The \fB\.gitsecret/keys\fR subdirectory permission is set to 700 to make gnupg happy\.
.
.IP "" 0
.
.P
See git\-secret(7) \fIhttps://git\-secret\.io/git\-secret\fR for information about renaming the \.gitsecret folder with the \fBSECRETS_DIR\fR environment variable, and changing the extension \fBgit\-secret\fR uses for secret files with the \fBSECRETS_EXTENSION\fR environment variable\.
.
.SH "OPTIONS"
.
.nf

\-h  \- shows this help\.
.
.fi
.
.SH "MANUAL"
Run \fBman git\-secret\-init\fR to see this document\.
.
.SH "SEE ALSO"
git\-secret\-usage(1) \fIhttps://git\-secret\.io/git\-secret\-usage\fR, git\-secret\-tell(1) \fIhttps://git\-secret\.io/git\-secret\-tell\fR
